/**
 * Settings Configuration
 * Organizes all script settings into logical groups for the settings UI
 */
import { t } from '../utils/i18n.js';

export const settingsGroups = {
    ironCow: {
        title: t('Iron Cow Mode', '铁牛模式'),
        icon: '🐄',
        settings: {
            ironCow_enabled: {
                id: 'ironCow_enabled',
                label: t('Iron Cow Mode', '铁牛模式'),
                type: 'checkbox',
                default: false,
                hidden: true,
                help: t('Disable all market and profit features for a no-marketplace playthrough.', '禁用所有市场和利润功能，以进行无市场模式的游玩。'),
            },
        },
    },
    general: {
        title: t('General Settings', '通用设置'),
        icon: '⚙️',
        settings: {
            networkAlert: {
                id: 'networkAlert',
                label: t('Show alert when market price data cannot be fetched', '当无法获取市场价格数据时显示警报'),
                type: 'checkbox',
                default: true,
            },
            chatCommands: {
                id: 'chatCommands',
                label: t('Enable chat commands (/item, /wiki, /market)', '启用聊天命令 (/item, /wiki, /market)'),
                type: 'checkbox',
                default: true,
                help: t('Type /item, /wiki, or /market followed by an item name in chat. Example: /item radiant fiber', '在聊天中输入 /item, /wiki 或 /market 后跟物品名称。例如: /item radiant fiber'),
            },
            chat_mentionTracker: {
                id: 'chat_mentionTracker',
                label: t('Show badge when mentioned in chat', '在聊天中被提及时显示徽章'),
                type: 'checkbox',
                default: true,
                help: t('Displays a red badge on chat tabs when someone @mentions you', '当有人 @提及 你时，在聊天标签上显示红色徽章'),
            },
            chat_popOut: {
                id: 'chat_popOut',
                label: t('Enable Pop-out Chat Window button', '启用弹出聊天窗口按钮'),
                type: 'checkbox',
                default: true,
                help: t('Adds a button to the chat panel to open chat in a separate browser window with multi-channel split view', '在聊天面板添加一个按钮，在单独的浏览器窗口中打开带有频道分屏的聊天室'),
            },
            chatHistoryExtender: {
                id: 'chatHistoryExtender',
                label: t('Chat: Extend chat history', '聊天: 延长聊天记录'),
                type: 'checkbox',
                default: true,
                help: t('Preserves messages that the game removes from the live buffer, keeping them visible above the live chat', '保留游戏从实时缓冲区中移除的消息，使其在实时聊天上方保持可见'),
            },
            chatHistoryExtender_maxHistory: {
                id: 'chatHistoryExtender_maxHistory',
                label: t('Chat: Max messages to retain per tab', '聊天: 每个标签页保留的最大消息数'),
                type: 'text',
                default: '150',
            },
            altClickNavigation: {
                id: 'altClickNavigation',
                label: t('Alt+click items to navigate to crafting/gathering or dictionary', 'Alt+点击物品可导航至制作/采集或字典'),
                type: 'checkbox',
                default: true,
                help: t('Hold Alt/Option and click any item to navigate to its crafting/gathering page, or item dictionary if not craftable', '按住 Alt/Option 并点击任何物品即可导航至其制作/采集页面，如果不可制作则导航至物品字典'),
            },
            collectionNavigation: {
                id: 'collectionNavigation',
                label: t('Add navigation buttons to collection items', '在收藏物品上添加导航按钮'),
                type: 'checkbox',
                default: true,
                help: t('Adds View Action and Item Dictionary buttons when clicking collection items', '点击收藏物品时添加“查看行动”和“物品字典”按钮'),
            },
            queueMonitor: {
                id: 'queueMonitor',
                label: t('Cross-character queue monitor', '跨角色队列监控'),
                type: 'checkbox',
                default: false,
                help: t('Shows estimated queue time remaining for your other characters in a floating widget', '在浮动小部件中显示其他角色的预计剩余排队时间'),
            },
        },
    },

    actionPanel: {
        title: t('Action Panel Enhancements', '行动面板增强'),
        icon: '⚡',
        settings: {
            totalActionTime: {
                id: 'totalActionTime',
                label: t('Top left: Action bar display mode', '左上角: 行动条显示模式'),
                type: 'select',
                default: 'full',
                options: [
                    { value: 'full', label: t('Full Details (all stats + time)', '完整详情 (所有属性 + 时间)') },
                    { value: 'compact', label: t('Compact (all stats, limited width)', '紧凑 (所有属性, 限制宽度)') },
                    { value: 'minimal', label: t('Minimal (remaining + time only)', '极简 (仅剩余 + 时间)') },
                ],
                help: t('Choose what information to display in the action bar. Full shows all stats, Compact limits width for wide monitors, Minimal shows only remaining actions and time to complete.', '选择要在行动条中显示的信息。完整显示所有统计数据，紧凑模式为宽屏显示器限制宽度，极简模式仅显示剩余行动和完成时间。'),
            },
            actionPanel_totalTime: {
                id: 'actionPanel_totalTime',
                label: t('Action panel: Total time, times to reach target level, exp/hour', '行动面板: 总时间, 达到目标等级的次数, 经验/小时'),
                type: 'checkbox',
                default: true,
            },
            actionPanel_totalTime_quickInputs: {
                id: 'actionPanel_totalTime_quickInputs',
                label: t('Action panel: Quick input buttons (hours, count presets, Max)', '行动面板: 快捷输入按钮 (小时, 数量预设, 最大值)'),
                type: 'checkbox',
                default: true,
            },
            actionPanel_quickInputs_countPresets: {
                id: 'actionPanel_quickInputs_countPresets',
                label: t('Action panel: Custom count presets (comma-separated, e.g. 100,1000,1000000)', '行动面板: 自定义数量预设 (逗号分隔，例如 100,1000,1000000)'),
                type: 'text',
                default: '',
            },
            actionPanel_quickInputs_hourPresets: {
                id: 'actionPanel_quickInputs_hourPresets',
                label: t('Action panel: Custom hour presets (comma-separated, e.g. 0.5,1,24,168,720)', '行动面板: 自定义小时预设 (逗号分隔，例如 0.5,1,24,168,720)'),
                type: 'text',
                default: '',
            },
            actionPanel_foragingTotal: {
                id: 'actionPanel_foragingTotal',
                label: t('Action panel: Overall profit for multi-outcome foraging', '行动面板: 多产出采集的整体利润'),
                type: 'checkbox',
                default: true,
            },
            actionQueue: {
                id: 'actionQueue',
                label: t('Queued actions: Show total time and completion time', '排队行动: 显示总时间和完成时间'),
                type: 'checkbox',
                default: true,
            },
            actionPanel_enhanceMatLimitProtections: {
                id: 'actionPanel_enhanceMatLimitProtections',
                label: t('Enhancement material limit: Include protection items', '强化材料限制: 包含保护物品'),
                type: 'checkbox',
                default: true,
                help: t('When enabled, protection item availability is factored into the material limit estimate. Disable to see material limit based only on enhancement materials.', '启用时，将考虑保护物品的可用性来估算材料限制。禁用时，仅基于强化材料查看材料限制。'),
            },
            actionQueue_valueMode: {
                id: 'actionQueue_valueMode',
                label: t('Queued actions: Value calculation mode', '排队行动: 价值计算模式'),
                type: 'select',
                default: 'profit',
                options: [
                    { value: 'profit', label: t('Total Profit (revenue - all costs)', '总利润 (收入 - 所有成本)') },
                    { value: 'estimated_value', label: t('Estimated Value (revenue after tax)', '预估价值 (税后收入)') },
                ],
                help: t('Choose how to calculate the total value for queued actions. Profit shows net earnings after materials and drinks. Estimated Value shows gross revenue after market tax (always positive).', '选择如何计算排队行动的总价值。利润显示扣除材料和饮料后的净收益。预估价值显示扣除市场税后的总收入（始终为正）。'),
            },
            actionPanel_outputTotals: {
                id: 'actionPanel_outputTotals',
                label: t('Action panel: Show total expected outputs below per-action outputs', '行动面板: 在每次行动产出下方显示预期总产出'),
                type: 'checkbox',
                default: true,
                help: t('Displays calculated totals when you enter a quantity in the action input', '在行动输入框中输入数量时显示计算后的总数'),
            },
            actionPanel_maxProduceable: {
                id: 'actionPanel_maxProduceable',
                label: t('Action panel: Show max produceable count on crafting actions', '行动面板: 在制作行动上显示最大可制作数量'),
                type: 'checkbox',
                default: true,
                help: t('Displays how many items you can make based on current inventory', '显示根据当前库存可以制作的物品数量'),
            },
            actionPanel_showProfitPerHour: {
                id: 'actionPanel_showProfitPerHour',
                label: t('Action page: Show profit/hr on tiles', '行动页面: 在卡片上显示利润/小时'),
                type: 'checkbox',
                default: true,
                help: t('Displays profit/hr on each action tile in the action list page', '在行动列表页面的每个行动卡片上显示利润/小时'),
            },
            actionPanel_showProfitDetail: {
                id: 'actionPanel_showProfitDetail',
                label: t('Action panel: Show profitability detail', '行动面板: 显示利润详情'),
                type: 'checkbox',
                default: true,
                help: t('Displays the profitability breakdown section inside gathering, production, and alchemy action panels', '在采集、生产和炼金行动面板内显示盈利能力明细部分'),
            },
            actionPanel_showLevelProgress: {
                id: 'actionPanel_showLevelProgress',
                label: t('Action panel: Show level progress', '行动面板: 显示等级进度'),
                type: 'checkbox',
                default: true,
                help: t('Displays XP and level progress estimates inside action panels', '在行动面板内显示经验和等级进度估算'),
            },
            actionPanel_showExpPerHour: {
                id: 'actionPanel_showExpPerHour',
                label: t('Action page: Show exp/hr on tiles', '行动页面: 在卡片上显示经验/小时'),
                type: 'checkbox',
                default: true,
                help: t('Displays exp/hr on each action tile in the action list page', '在行动列表页面的每个行动卡片上显示经验/小时'),
            },
            actionPanel_hideNegativeProfit: {
                id: 'actionPanel_hideNegativeProfit',
                label: t('Action panel: Hide actions with negative profit', '行动面板: 隐藏负利润行动'),
                type: 'checkbox',
                default: false,
                help: t('Hides action panels that would result in a loss (negative profit/hr)', '隐藏会导致亏损（利润/小时为负）的行动面板'),
            },
            requiredMaterials: {
                id: 'requiredMaterials',
                label: t('Action panel: Show total required and missing materials', '行动面板: 显示所需的总材料和缺失材料'),
                type: 'checkbox',
                default: true,
                help: t('Displays total materials needed and shortfall when entering quantity', '在输入数量时显示所需的总材料和缺口'),
            },
            alchemy_profitDisplay: {
                id: 'alchemy_profitDisplay',
                label: t('Alchemy panel: Show profit calculator', '炼金面板: 显示利润计算器'),
                type: 'checkbox',
                default: true,
                help: t('Displays profit/hour and profit/day for alchemy actions based on success rate and market prices', '根据成功率和市场价格显示炼金行动的利润/小时和利润/天'),
            },
            alchemy_bestItems: {
                id: 'alchemy_bestItems',
                label: t('Alchemy panel: Show best items button', '炼金面板: 显示最佳物品按钮'),
                type: 'checkbox',
                default: true,
                help: t('Adds a button to see items ranked by profit or XP for each alchemy type.', '添加一个按钮以查看每种炼金类型按利润或经验排序的物品。'),
            },
            alchemy_transmuteHistory: {
                id: 'alchemy_transmuteHistory',
                label: t('Alchemy panel: Track and view transmute session history', '炼金面板: 追踪并查看转化会话历史记录'),
                type: 'checkbox',
                default: true,
                help: t('Records transmutation sessions and displays history in a viewer tab in the Alchemy panel', '记录转化会话并在炼金面板的查看器标签页中显示历史记录'),
            },
            alchemy_coinifyHistory: {
                id: 'alchemy_coinifyHistory',
                label: t('Alchemy panel: Track and view coinify session history', '炼金面板: 追踪并查看化币会话历史记录'),
                type: 'checkbox',
                default: true,
                help: t('Records coinify sessions and displays history in a viewer tab in the Alchemy panel', '记录化币会话并在炼金面板的查看器标签页中显示历史记录'),
            },
            alchemy_decomposeHistory: {
                id: 'alchemy_decomposeHistory',
                label: t('Alchemy panel: Track and view decompose session history', '炼金面板: 追踪并查看分解会话历史记录'),
                type: 'checkbox',
                default: true,
                help: t('Records decompose sessions and displays history in a viewer tab in the Alchemy panel', '记录分解会话并在炼金面板的查看器标签页中显示历史记录'),
            },
            actions_missingMaterialsButton: {
                id: 'actions_missingMaterialsButton',
                label: t('Show "Missing Mats Marketplace" button on production panels', '在生产面板上显示“缺失材料市场”按钮'),
                type: 'checkbox',
                default: true,
                help: t('Adds button to production panels that opens marketplace with tabs for missing materials', '在生产面板上添加按钮，该按钮会打开市场并带有缺失材料的标签页'),
            },
            actions_missingMaterialsButton_ignoreQueue: {
                id: 'actions_missingMaterialsButton_ignoreQueue',
                label: t('Ignore queued actions when calculating missing materials', '计算缺失材料时忽略排队行动'),
                type: 'checkbox',
                default: false,
                help: t('When enabled, missing materials calculation only considers current action request, ignoring materials already reserved by queued actions. Default (off) accounts for queue.', '启用时，缺失材料计算仅考虑当前行动请求，忽略排队行动已保留的材料。默认（关闭）则将队列计算在内。'),
            },
            actions_budgetCalculator: {
                id: 'actions_budgetCalculator',
                label: t('Action panel: Budget calculator', '行动面板: 预算计算器'),
                type: 'checkbox',
                default: true,
                help: t('Adds a budget input below the Missing Mats button. Enter a gold budget (e.g. 50m) to calculate how many units you can produce by buying missing tradeable materials at ask price.', '在缺失材料按钮下方添加预算输入框。输入金币预算（例如 50m）来计算按照卖出价购买缺失的可交易材料后可以生产多少单位。'),
            },
            actionPanel_bestCraftingPlan: {
                id: 'actionPanel_bestCraftingPlan',
                label: t('Action panel: Show best crafting plan', '行动面板: 显示最佳制作方案'),
                type: 'checkbox',
                default: true,
                help: t('Shows the cheapest way to obtain a crafted item by comparing buy vs craft at each material tier.', '通过比较每个材料等级的购买和制作成本，显示获取制作物品的最便宜方式。'),
            },
            actionPanel_craftingPlanBuyIntermediates: {
                id: 'actionPanel_craftingPlanBuyIntermediates',
                label: t('Action panel: Crafting plan buys raw materials only', '行动面板: 制作方案仅购买原材料'),
                type: 'checkbox',
                default: false,
                help: t('Always craft items that have a recipe — only buy uncraftable raw materials from the market.', '始终制作有配方的物品 — 仅从市场购买不可制作的原材料。'),
            },
            lootLogStats: {
                id: 'lootLogStats',
                label: t('Loot Log Statistics', '战利品日志统计'),
                type: 'checkbox',
                default: true,
                help: t('Display total value, average time, and daily output in loot logs', '在战利品日志中显示总价值、平均时间和每日产出'),
            },
            inventoryCountDisplay: {
                id: 'inventoryCountDisplay',
                label: t('Action panels: Show current inventory count of output item', '行动面板: 显示产出物品的当前库存数量'),
                type: 'checkbox',
                default: true,
                help: t('Shows how many of the output item you currently own, on action tiles and in the action detail panel', '在行动卡片和行动详情面板上显示你目前拥有多少个该产出物品'),
            },
            actions_pinnedPage: {
                id: 'actions_pinnedPage',
                label: t('Pinned actions page in navigation bar', '在导航栏中固定行动页面'),
                type: 'checkbox',
                default: true,
                help: t('Adds a Pinned button to the left nav bar that shows all pinned actions in one list with skill, level, profit/hr, and XP/hr.', '在左侧导航栏中添加一个固定按钮，该按钮在一个列表中显示所有固定的行动，包含技能、等级、利润/小时和经验/小时。'),
            },
        },
    },

    tooltips: {
        title: t('Item Tooltip Enhancements', '物品工具提示增强'),
        icon: '💬',
        settings: {
            itemTooltip_prices: {
                id: 'itemTooltip_prices',
                label: t('Show 24-hour average market prices', '显示24小时平均市场价格'),
                type: 'checkbox',
                default: true,
            },
            itemTooltip_profit: {
                id: 'itemTooltip_profit',
                label: t('Show production cost and profit', '显示生产成本和利润'),
                type: 'checkbox',
                default: true,
            },
            itemTooltip_detailedProfit: {
                id: 'itemTooltip_detailedProfit',
                label: t('Show detailed materials breakdown in profit display', '在利润显示中展示详细的材料明细'),
                type: 'checkbox',
                default: false,
                help: t('Shows material costs table with Ask/Bid prices, actions/hour, and profit breakdown', '显示包含买入/卖出价格、每小时行动次数和利润明细的材料成本表'),
            },
            itemTooltip_multiActionProfit: {
                id: 'itemTooltip_multiActionProfit',
                label: t('Show profit comparison for all item actions', '显示所有物品行动的利润比较'),
                type: 'checkbox',
                default: false,
                help: t('Displays best profit/hr highlighted, with other alternative actions (craft, coinify, decompose, transmute) summarized below', '高亮显示最佳利润/小时，并在下方总结其他替代行动（制作、化币、分解、转化）'),
            },
            itemTooltip_expectedValue: {
                id: 'itemTooltip_expectedValue',
                label: t('Show expected value for openable containers', '显示可开启容器的期望价值'),
                type: 'checkbox',
                default: true,
            },
            expectedValue_showDrops: {
                id: 'expectedValue_showDrops',
                label: t('Expected value drop display', '期望价值掉落显示'),
                type: 'select',
                default: 'All',
                options: [
                    { value: 'Top 5', label: t('Top 5', '前 5 名') },
                    { value: 'Top 10', label: t('Top 10', '前 10 名') },
                    { value: 'All', label: t('All Drops', '所有掉落') },
                    { value: 'None', label: t('Summary Only', '仅显示摘要') },
                ],
            },
            expectedValue_respectPricingMode: {
                id: 'expectedValue_respectPricingMode',
                label: t('Use pricing mode for expected value calculations', '在期望价值计算中使用定价模式'),
                type: 'checkbox',
                default: true,
            },
            showConsumTips: {
                id: 'showConsumTips',
                label: t('HP/MP consumables: Restore speed, cost performance', 'HP/MP 消耗品: 恢复速度、性价比'),
                type: 'checkbox',
                default: true,
            },
            dungeonTokenTooltips: {
                id: 'dungeonTokenTooltips',
                label: t('Currency tooltips: Show shop values for tokens, seals, and cowbells', '代币工具提示: 显示代币、印章和牛铃的商店价值'),
                type: 'checkbox',
                default: true,
            },
            enhanceSim: {
                id: 'enhanceSim',
                label: t('Show enhancement simulator calculations', '显示强化模拟器计算结果'),
                type: 'checkbox',
                default: true,
            },
            enhanceSim_showConsumedItemsDetail: {
                id: 'enhanceSim_showConsumedItemsDetail',
                label: t('Enhancement tooltips: Show detailed breakdown for consumed items', '强化工具提示: 显示消耗物品的详细明细'),
                type: 'checkbox',
                default: false,
                help: t("When enabled, shows base/materials/protection breakdown for each consumed item in Philosopher's Mirror calculations", "启用时，在贤者之镜计算中显示每个消耗物品的基础/材料/保护明细"),
            },
            enhanceSim_baseItemCraftingCost: {
                id: 'enhanceSim_baseItemCraftingCost',
                label: t('Enhancement path: Use crafting cost for base item if cheaper', '强化路径: 如果更便宜则使用基础物品的制作成本'),
                type: 'checkbox',
                default: false,
                help: t('When enabled, uses the lower of crafting cost or market price for the base item in enhancement path calculations, applied independently to both the Ask and Bid columns', '启用时，在强化路径计算中使用基础物品较低的制作成本或市场价格，独立应用于卖出和买入列'),
            },
            itemTooltip_gathering: {
                id: 'itemTooltip_gathering',
                label: t('Show gathering sources and profit', '显示采集来源和利润'),
                type: 'checkbox',
                default: true,
                help: t('Shows gathering actions that produce this item (foraging, woodcutting, milking)', '显示产生此物品的采集行动（觅食、伐木、挤奶）'),
            },
            itemTooltip_gatheringRareDrops: {
                id: 'itemTooltip_gatheringRareDrops',
                label: t('Show rare drops from gathering', '显示采集时的稀有掉落'),
                type: 'checkbox',
                default: true,
                help: t('Shows rare find drops from gathering zones (e.g., Thread of Expertise from Asteroid Belt)', '显示采集区域的稀有掉落（例如：小行星带的专业知识之线）'),
            },
            itemTooltip_abilityStatus: {
                id: 'itemTooltip_abilityStatus',
                label: t('Show ability book status', '显示技能书状态'),
                type: 'checkbox',
                default: true,
                help: t('Shows whether ability is learned and current level/progress on ability book tooltips', '在技能书工具提示上显示技能是否已学习以及当前等级/进度'),
            },
            itemTooltip_enhancementMilestones: {
                id: 'itemTooltip_enhancementMilestones',
                label: t('Show enhancement milestones (+5/+7/+10/+12)', '显示强化里程碑 (+5/+7/+10/+12)'),
                type: 'checkbox',
                default: false,
                help: t('Shows expected cost and XP to reach +5, +7, +10, and +12 on unenhanced equipment tooltips', '在未强化装备的工具提示上显示达到 +5、+7、+10 和 +12 的预期成本和经验'),
            },
            itemTooltip_enhancementPath: {
                id: 'itemTooltip_enhancementPath',
                label: t('Show enhancement path on enhanced items', '在已强化物品上显示强化路径'),
                type: 'checkbox',
                default: true,
                help: t('Shows the optimal enhancement path cost breakdown when hovering over enhanced (+1 to +20) items', '悬停在已强化（+1 到 +20）物品上时显示最佳强化路径成本明细'),
            },
            itemTooltip_pinTop: {
                id: 'itemTooltip_pinTop',
                label: t('Pin tooltips to top-center of screen', '将工具提示固定在屏幕顶部居中'),
                type: 'checkbox',
                default: false,
                help: t('Forces item tooltips to always appear centered at the top of the screen instead of near the hovered item', '强制物品工具提示始终显示在屏幕顶部居中，而不是在悬停物品附近'),
            },
        },
    },

    enhancementSimulator: {
        title: t('Enhancement Simulator Settings', '强化模拟器设置'),
        icon: '✨',
        settings: {
            enhanceSim_autoDetect: {
                id: 'enhanceSim_autoDetect',
                label: t('Auto-detect your stats (false = use settings below)', '自动检测您的属性（关闭 = 使用以下设置）'),
                type: 'checkbox',
                default: false,
                help: t('Most players should leave this off to see realistic professional enhancer costs', '大多数玩家应将其关闭，以查看实际专业强化师的成本'),
            },
            enhanceSim_enhancingLevel: {
                id: 'enhanceSim_enhancingLevel',
                label: t('Enhancing skill level', '强化技能等级'),
                type: 'number',
                default: 140,
                min: 1,
                max: 150,
                help: t('Default: 140 (professional enhancer level)', '默认值: 140 (专业强化师等级)'),
                disabledBy: 'enhanceSim_autoDetect',
            },
            enhanceSim_houseLevel: {
                id: 'enhanceSim_houseLevel',
                label: t('Observatory house room level', '天文台房屋房间等级'),
                type: 'number',
                default: 8,
                min: 0,
                max: 8,
                help: t('Default: 8 (max level)', '默认值: 8 (满级)'),
                disabledBy: 'enhanceSim_autoDetect',
            },
            enhanceSim_toolBonus: {
                id: 'enhanceSim_toolBonus',
                label: t('Tool success bonus %', '工具成功率加成 %'),
                type: 'number',
                default: 6.05,
                min: 0,
                max: 30,
                step: 0.01,
                help: t('Default: 6.05 (Celestial Enhancer +13)', '默认值: 6.05 (天体强化器 +13)'),
                disabledBy: 'enhanceSim_autoDetect',
            },
            enhanceSim_speedBonus: {
                id: 'enhanceSim_speedBonus',
                label: t('Speed bonus %', '速度加成 %'),
                type: 'number',
                default: 48.5,
                min: 0,
                max: 100,
                step: 0.1,
                help: t("Default: 48.5 (All enhancing gear +10: Body/Legs/Hands + Philosopher's Necklace)", "默认值: 48.5 (所有强化装备 +10: 身体/腿部/手部 + 贤者项链)"),
                disabledBy: 'enhanceSim_autoDetect',
            },
            enhanceSim_blessedTea: {
                id: 'enhanceSim_blessedTea',
                label: t('Blessed Tea active', '受福茶已激活'),
                type: 'checkbox',
                default: true,
                help: t('Professional enhancers use this to reduce attempts', '专业强化师使用此功能来减少尝试次数'),
                disabledBy: 'enhanceSim_autoDetect',
            },
            enhanceSim_ultraEnhancingTea: {
                id: 'enhanceSim_ultraEnhancingTea',
                label: t('Ultra Enhancing Tea active', '究极强化茶已激活'),
                type: 'checkbox',
                default: true,
                help: t('Provides +8 base skill levels (scales with drink concentration)', '提供 +8 基础技能等级（随饮料浓度增加）'),
                disabledBy: 'enhanceSim_autoDetect',
            },
            enhanceSim_superEnhancingTea: {
                id: 'enhanceSim_superEnhancingTea',
                label: t('Super Enhancing Tea active', '超级强化茶已激活'),
                type: 'checkbox',
                default: false,
                help: t('Provides +6 base skill levels (Ultra is better)', '提供 +6 基础技能等级（究极强化茶更好）'),
                disabledBy: 'enhanceSim_autoDetect',
            },
            enhanceSim_enhancingTea: {
                id: 'enhanceSim_enhancingTea',
                label: t('Enhancing Tea active', '强化茶已激活'),
                type: 'checkbox',
                default: false,
                help: t('Provides +3 base skill levels (Ultra is better)', '提供 +3 基础技能等级（究极强化茶更好）'),
                disabledBy: 'enhanceSim_autoDetect',
            },
            enhanceSim_drinkConcentration: {
                id: 'enhanceSim_drinkConcentration',
                label: t('Drink Concentration %', '饮料浓度 %'),
                type: 'number',
                default: 12.9,
                min: 0,
                max: 20,
                step: 0.1,
                help: t('Default: 12.9 (Guzzling Pouch +10)', '默认值: 12.9 (暴饮袋 +10)'),
                disabledBy: 'enhanceSim_autoDetect',
            },
        },
    },

    enhancementTracker: {
        title: t('Enhancement Tracker', '强化追踪器'),
        icon: '📊',
        settings: {
            enhancementTracker: {
                id: 'enhancementTracker',
                label: t('Enable Enhancement Tracker', '启用强化追踪器'),
                type: 'checkbox',
                default: false,
                help: t('Track enhancement attempts, costs, and statistics', '追踪强化尝试次数、成本和统计数据'),
            },
            enhancementTracker_showOnlyOnEnhancingScreen: {
                id: 'enhancementTracker_showOnlyOnEnhancingScreen',
                label: t('Show tracker only on Enhancing screen', '仅在强化界面显示追踪器'),
                type: 'checkbox',
                default: false,
                help: t('Hide tracker when not on the Enhancing screen', '不在强化界面时隐藏追踪器'),
            },
            enhancementXPH: {
                id: 'enhancementXPH',
                label: t('Enhancement: XPH calculator', '强化: 经验/小时计算器'),
                type: 'checkbox',
                default: true,
                help: t('Ranks all enhanceable items by expected XP per hour at your current stats', '根据当前属性下的预期每小时经验对所有可强化物品进行排名'),
            },
            enhancementXPH_maxLevel: {
                id: 'enhancementXPH_maxLevel',
                label: t('Enhancement XPH: Default max enhancement level (1–20)', '强化经验计算: 默认最高强化等级 (1–20)'),
                type: 'text',
                default: '6',
            },
            enhancementXPH_protectFrom: {
                id: 'enhancementXPH_protectFrom',
                label: t('Enhancement XPH: Default protect from level (0 = no protection)', '强化经验计算: 默认保护起始等级 (0 = 无保护)'),
                type: 'text',
                default: '0',
            },
        },
    },

    economy: {
        title: t('Economy & Inventory', '经济与库存'),
        icon: '💰',
        settings: {
            networth: {
                id: 'networth',
                label: t('Top right: Show current assets (net worth)', '右上角: 显示当前资产 (净值)'),
                type: 'checkbox',
                default: true,
                help: t('Enhanced items valued by enhancement simulator', '已强化物品价值由强化模拟器评估'),
            },
            invWorth: {
                id: 'invWorth',
                label: t('Below inventory: Show inventory summary', '库存下方: 显示库存摘要'),
                type: 'checkbox',
                default: true,
            },
            invSort: {
                id: 'invSort',
                label: t('Sort inventory items by value', '按价值对库存物品进行排序'),
                type: 'checkbox',
                default: true,
            },
            invSort_showBadges: {
                id: 'invSort_showBadges',
                label: t('Show stack value badges when sorting by Ask/Bid', '按卖出/买入排序时显示堆叠价值徽章'),
                type: 'checkbox',
                default: false,
            },
            invSort_badgesOnNone: {
                id: 'invSort_badgesOnNone',
                label: t('Badge type when "None" sort is selected', '选择“无”排序时的徽章类型'),
                type: 'select',
                default: 'None',
                options: [t('None', '无'), t('Ask', '卖出价'), t('Bid', '买入价')],
            },
            invSort_netOfTax: {
                id: 'invSort_netOfTax',
                label: t('Show badge values net of market tax', '显示扣除市场税后的徽章价值'),
                type: 'checkbox',
                default: false,
            },
            invSort_sortEquipment: {
                id: 'invSort_sortEquipment',
                label: t('Enable sorting for Equipment category', '启用装备类别的排序'),
                type: 'checkbox',
                default: false,
            },
            invBadgePrices: {
                id: 'invBadgePrices',
                label: t('Show price badges on item icons', '在物品图标上显示价格徽章'),
                type: 'checkbox',
                default: false,
                help: t('Displays per-item ask and bid prices on inventory items', '在库存物品上显示单件物品的卖出和买入价'),
            },
            invCategoryTotals: {
                id: 'invCategoryTotals',
                label: t('Show category totals in inventory', '在库存中显示类别总额'),
                type: 'checkbox',
                default: true,
                help: t('Displays the total market value of all items in each inventory category', '显示每个库存类别中所有物品的市场总值'),
            },
            profitCalc_pricingMode: {
                id: 'profitCalc_pricingMode',
                label: t('Profit calculation pricing mode', '利润计算定价模式'),
                type: 'select',
                default: 'hybrid',
                options: [
                    { value: 'conservative', label: t('Buy: Ask / Sell: Bid (Instant Buy / Instant Sell)', '买: 卖出价 / 卖: 买入价 (秒买 / 秒卖)') },
                    { value: 'hybrid', label: t('Buy: Ask / Sell: Ask (Instant Buy / Patient Sell)', '买: 卖出价 / 卖: 卖出价 (秒买 / 耐心卖)') },
                    { value: 'optimistic', label: t('Buy: Bid / Sell: Ask (Patient Buy / Patient Sell)', '买: 买入价 / 卖: 卖出价 (耐心买 / 耐心卖)') },
                    { value: 'patientBuy', label: t('Buy: Bid / Sell: Bid (Patient Buy / Instant Sell)', '买: 买入价 / 卖: 买入价 (耐心买 / 秒卖)') },
                ],
            },
            profitCalc_pricingNaming: {
                id: 'profitCalc_pricingNaming',
                label: t('Pricing mode naming convention', '定价模式命名规范'),
                type: 'checkbox',
                default: false,
                help: t('Show pricing modes as "Instant Buy / Instant Sell" instead of "Buy: Ask / Sell: Bid"', '将定价模式显示为“秒买 / 秒卖”而不是“买: 卖出价 / 卖: 买入价”'),
            },
            profitCalc_keyPricingMode: {
                id: 'profitCalc_keyPricingMode',
                label: t('Key pricing mode', '钥匙定价模式'),
                type: 'select',
                default: 'ask',
                options: ['ask', 'bid'],
                help: t('Whether to use ask (instant buy) or bid (patient buy) prices when valuing dungeon keys in tooltips, networth, and combat income calculations.', '在工具提示、净值和战斗收入计算中评估副本钥匙价值时，使用卖出价（秒买）还是买入价（耐心买）。'),
            },
            profitCalc_customPriceOverrides: {
                id: 'profitCalc_customPriceOverrides',
                label: t('Custom price overrides', '自定义价格覆盖'),
                type: 'customPriceOverrides',
                default: {},
                help: t('Set custom buy/sell prices for specific items. Overrides marketplace prices in profit calculations.', '设置特定物品的自定义买入/卖出价格。在利润计算中覆盖市场价格。'),
            },
            actions_artisanMaterialMode: {
                id: 'actions_artisanMaterialMode',
                label: t('Missing materials: Artisan requirement mode', '缺失材料: 匠人要求模式'),
                type: 'select',
                default: 'expected',
                options: [
                    { value: 'expected', label: t('Expected value (average)', '期望值（平均）') },
                    { value: 'worst-case', label: t('Worst-case per action (ceil per craft)', '每次行动的最坏情况（每次制作向上取整）') },
                ],
                help: t('Choose how missing materials accounts for Artisan Tea reductions when suggesting what to buy.', '选择在建议购买什么时，缺失材料如何计算匠人茶的减少量。'),
            },
            networth_highEnhancementUseCost: {
                id: 'networth_highEnhancementUseCost',
                label: t('Use enhancement cost for highly enhanced items', '对高强化物品使用强化成本'),
                type: 'checkbox',
                default: true,
                help: t('Market prices are unreliable for highly enhanced items (+13 and above). Use calculated enhancement cost instead.', '高强化物品（+13 及以上）的市场价格不可靠。请改用计算的强化成本。'),
            },
            networth_highEnhancementMinLevel: {
                id: 'networth_highEnhancementMinLevel',
                label: t('Minimum enhancement level to use cost', '使用成本的最低强化等级'),
                type: 'select',
                default: 13,
                options: [
                    { value: 10, label: t('+10 and above', '+10 及以上') },
                    { value: 11, label: t('+11 and above', '+11 及以上') },
                    { value: 12, label: t('+12 and above', '+12 及以上') },
                    { value: 13, label: t('+13 and above (recommended)', '+13 及以上（推荐）') },
                    { value: 15, label: t('+15 and above', '+15 及以上') },
                ],
                help: t('Enhancement level at which to stop trusting market prices', '不再信任市场价格的强化等级'),
            },
            networth_includeCowbells: {
                id: 'networth_includeCowbells',
                label: t('Include cowbells in net worth', '将牛铃计入净值'),
                type: 'checkbox',
                default: false,
                help: t('Cowbells are not tradeable, but they have a value based on Bag of 10 Cowbells market price', '牛铃不可交易，但其价值基于“一袋 10 个牛铃”的市场价格'),
            },
            networth_includeTaskTokens: {
                id: 'networth_includeTaskTokens',
                label: t('Include task tokens in net worth', '将任务代币计入净值'),
                type: 'checkbox',
                default: true,
                help: t('Value task tokens based on expected value from Task Shop chests. Disable to exclude them from net worth.', '根据任务商店宝箱的期望价值来评估任务代币的价值。禁用以将其从净值中排除。'),
            },
            networth_abilityBooksAsInventory: {
                id: 'networth_abilityBooksAsInventory',
                label: t('Count ability books as inventory (Current Assets)', '将技能书计入库存（流动资产）'),
                type: 'checkbox',
                default: false,
                help: t('Move ability books from Fixed Assets to Current Assets inventory value. Useful if you plan to sell them.', '将技能书从固定资产转移到流动资产库存价值。如果你打算出售它们，这将非常有用。'),
            },
            networth_historyChart: {
                id: 'networth_historyChart',
                label: t('Enable net worth history chart', '启用净值历史记录图表'),
                type: 'checkbox',
                default: true,
                help: t('Records hourly net worth snapshots and shows a chart icon next to Total Net Worth. Disable to stop tracking and hide the chart button.', '记录每小时的净值快照，并在“总净值”旁边显示图表图标。禁用以停止跟踪并隐藏图表按钮。'),
            },
            autoAllButton: {
                id: 'autoAllButton',
                label: t('Auto-click "All" button when opening loot boxes', '打开战利品箱时自动点击“全部”按钮'),
                type: 'checkbox',
                default: true,
                help: t('Automatically clicks the "All" button when opening openable containers (crates, chests, caches)', '当打开可开启的容器（板条箱、宝箱、储藏箱）时自动点击“全部”按钮'),
            },
            autoAllButton_excludeSeals: {
                id: 'autoAllButton_excludeSeals',
                label: t('Auto-click "All": Skip Scroll of... items', '自动点击“全部”: 跳过卷轴...物品'),
                type: 'checkbox',
                default: true,
                help: t('When enabled, Scroll of... items from the Labyrinth are not auto-opened', '启用时，来自迷宫的“卷轴...”物品不会被自动打开'),
            },
        },
    },

    inventoryTabs: {
        title: t('Custom Inventory Tabs', '自定义库存标签页'),
        icon: '🗂️',
        settings: {
            inventoryTabs: {
                id: 'inventoryTabs',
                label: t('Custom Inventory Tabs: Enable', '自定义库存标签页: 启用'),
                type: 'checkbox',
                default: true,
                help: t('Adds a Toolasha tab to the character panel where you can organize inventory items into personal tabs.', '在角色面板添加 Toolasha 标签页，您可以在此将库存物品整理到个人标签页中。'),
            },
            inventoryTabs_showUnorganized: {
                id: 'inventoryTabs_showUnorganized',
                label: t('Custom Inventory Tabs: Show Unorganized bucket', '自定义库存标签页: 显示未整理类别'),
                type: 'checkbox',
                default: true,
                help: t('Show an "Unorganized" section containing all items not assigned to any tab.', '显示一个“未整理”部分，包含所有未分配到任何标签页的物品。'),
            },
            inventoryTabs_categoryAddAll: {
                id: 'inventoryTabs_categoryAddAll',
                label: t('Custom Inventory Tabs: Add all items when adding category', '自定义库存标签页: 添加类别时添加所有物品'),
                type: 'checkbox',
                default: false,
                hidden: true,
                help: t('When adding a category to a tab, add every item in that category (including items not in your inventory). When disabled, only items currently in your inventory are added.', '在向标签页添加类别时，添加该类别中的每个物品（包括库存中没有的物品）。禁用时，仅添加您当前库存中的物品。'),
            },
            inventoryTabs_defaultTab: {
                id: 'inventoryTabs_defaultTab',
                label: t('Custom Inventory Tabs: Show Toolasha tab by default', '自定义库存标签页: 默认显示 Toolasha 标签页'),
                type: 'checkbox',
                default: false,
                help: t('Hides the native Inventory tab and automatically activates the Toolasha tab whenever the character panel opens.', '隐藏原生库存标签页，并在每次打开角色面板时自动激活 Toolasha 标签页。'),
            },
            inventoryTabs_tileGap: {
                id: 'inventoryTabs_tileGap',
                label: t('Custom Inventory Tabs: Item spacing (px)', '自定义库存标签页: 物品间距 (px)'),
                type: 'number',
                default: 4,
                min: 0,
                max: 20,
                step: 1,
                help: t('Pixel gap between item tiles on the Toolasha tab.', 'Toolasha 标签页上物品卡片之间的像素间距。'),
            },
            inventoryTabs_loadoutIncludeConsumables: {
                id: 'inventoryTabs_loadoutIncludeConsumables',
                label: t('Custom Inventory Tabs: Include food & drinks when adding from loadout', '自定义库存标签页: 从预设中添加时包含食物和饮料'),
                type: 'checkbox',
                default: false,
                help: t('When adding items from a loadout to a tab, also include food and drink items.', '在将预设中的物品添加到标签页时，也包含食物和饮料物品。'),
            },
            inventoryTabs_topTabPriority: {
                id: 'inventoryTabs_topTabPriority',
                label: t('Custom Inventory Tabs: Items visible in topmost tab only', '自定义库存标签页: 物品仅在最顶层标签页中可见'),
                type: 'checkbox',
                default: true,
                help: t('When an item appears in multiple tabs, it only shows in the highest (topmost) tab that contains it. When disabled, collapsing a tab releases its items to lower tabs.', '当一个物品出现在多个标签页中时，它仅显示在包含它的最高（最顶层）标签页中。禁用时，折叠一个标签页会将其物品释放到较低的标签页。'),
            },
        },
    },

    skills: {
        title: t('Skills', '技能'),
        icon: '📚',
        settings: {
            simulateScrollEffects: {
                id: 'simulateScrollEffects',
                label: t('Skills: Simulate missing scroll effects in calculations', '技能: 在计算中模拟缺失的卷轴效果'),
                type: 'checkboxWithButton',
                buttonLabel: t('Defaults...', '默认设置...'),
                default: false,
                help: t('When enabled, profit/XP/speed calculations show hypothetical results as if selected scrolls were active. Configure default scrolls with the button; override per-loadout from the Loadouts panel.', '启用时，利润/经验/速度计算将显示假设选定的卷轴已激活的结果。使用按钮配置默认卷轴；在预设面板中可以覆盖每个预设。'),
            },
            xpTracker: {
                id: 'xpTracker',
                label: t('Left sidebar: Show XP/hr rate on skill bars', '左侧边栏: 在技能条上显示经验/小时速率'),
                type: 'checkbox',
                default: true,
                help: t('Displays live XP/hr rate under each skill bar in the navigation panel', '在导航面板中每个技能条下方显示实时经验/小时速率'),
            },
            xpTracker_timeTillLevel: {
                id: 'xpTracker_timeTillLevel',
                label: t('Skill tooltip: Show time till next level', '技能工具提示: 显示到下一级的时间'),
                type: 'checkbox',
                default: true,
                help: t('Shows estimated time remaining until the next level in the skill hover tooltip (based on current XP/hr)', '在技能悬停工具提示中显示到下一级的预估剩余时间（基于当前经验/小时）'),
            },
            skillRemainingXP: {
                id: 'skillRemainingXP',
                label: t('Left sidebar: Show remaining XP to next level', '左侧边栏: 显示到下一级的剩余经验'),
                type: 'checkbox',
                default: true,
                help: t('Displays how much XP needed to reach the next level under skill progress bars', '在技能进度条下方显示升到下一级还需要多少经验'),
            },
            skillRemainingXP_blackBorder: {
                id: 'skillRemainingXP_blackBorder',
                label: t('Remaining XP: Add black text border for better visibility', '剩余经验: 添加黑色文字描边以提高可见度'),
                type: 'checkbox',
                default: true,
                help: 'Adds a black outline/shadow to the XP text for better readability against progress bars',
            },
            skillbook: {
                id: 'skillbook',
                label: t('Skill books: Show books needed to reach target level (in the ability book item dictionary window)', '技能书: 显示达到目标等级所需的技能书数量（在技能书物品字典窗口中）'),
                type: 'checkbox',
                default: true,
            },
        },
    },

    combat: {
        title: t('Combat Features', '战斗功能'),
        icon: '⚔️',
        settings: {
            combatScore: {
                id: 'combatScore',
                label: t('Profile panel: Show gear score', '个人资料面板: 显示装备评分'),
                type: 'checkbox',
                default: true,
            },
            abilitiesTriggers: {
                id: 'abilitiesTriggers',
                label: t('Profile panel: Show abilities & triggers', '个人资料面板: 显示技能和触发器'),
                type: 'checkbox',
                default: true,
                help: t('Displays equipped abilities, consumables, and their combat triggers below the profile', '在个人资料下方显示已装备的技能、消耗品及其战斗触发器'),
            },
            characterCard: {
                id: 'characterCard',
                label: t('Profile panel: Show View Card button', '个人资料面板: 显示“查看卡片”按钮'),
                type: 'checkbox',
                default: true,
                help: t('Adds button to open character sheet in external viewer', '添加按钮以在外部查看器中打开角色卡片'),
            },
            dungeonTracker: {
                id: 'dungeonTracker',
                label: t('Dungeon Tracker: Real-time progress tracking', '副本追踪器: 实时进度追踪'),
                type: 'checkbox',
                default: true,
                help: t('Tracks dungeon runs with server-validated duration from party messages', '通过队伍消息追踪具有服务器验证持续时间的副本次数'),
            },
            dungeonTrackerUI: {
                id: 'dungeonTrackerUI',
                label: t('Show Dungeon Tracker UI panel', '显示副本追踪器用户界面面板'),
                type: 'checkbox',
                default: true,
                help: t('Displays dungeon progress panel with wave counter, run history, and statistics', '显示带有波次计数器、运行历史和统计数据的副本进度面板'),
            },
            dungeonTrackerChatAnnotations: {
                id: 'dungeonTrackerChatAnnotations',
                label: t('Show run time in party chat', '在队伍聊天中显示运行时间'),
                type: 'checkbox',
                default: true,
                help: t('Adds colored timer annotations to "Key counts" messages (green if fast, red if slow)', '为“钥匙计数”消息添加彩色计时器注释（快为绿色，慢为红色）'),
            },
            labyrinthTracker: {
                id: 'labyrinthTracker',
                label: t('Labyrinth best level tracker', '迷宫最佳层数追踪器'),
                type: 'checkbox',
                default: true,
                help: t('Tracks the highest recommended level enemy defeated per monster type and shows it in the Automation tab', '追踪每种怪物类型击败的最高推荐等级敌人，并在自动化标签页中显示'),
            },
            labyrinthShopPrices: {
                id: 'labyrinthShopPrices',
                label: t('Labyrinth Shop: Show market prices', '迷宫商店: 显示市场价格'),
                type: 'checkbox',
                default: true,
                help: t('Shows ask/bid market prices on tradeable items in the Labyrinth Shop tab', '在迷宫商店标签页中显示可交易物品的市场卖出/买入价格'),
            },
            combatBattleCounter: {
                id: 'combatBattleCounter',
                label: t('Show battle/wave counter in current action panel during combat', '战斗期间在当前行动面板中显示战斗/波次计数器'),
                type: 'checkbox',
                default: true,
                help: t('Displays "Battle #N" for regular zones or "Wave N" for dungeons in the top-left action panel', '在左上角行动面板中为普通区域显示“战斗 #N”或为副本显示“波次 N”'),
            },
            combatSummary: {
                id: 'combatSummary',
                label: t('Combat Summary: Show detailed statistics on return', '战斗摘要: 返回时显示详细统计数据'),
                type: 'checkbox',
                default: true,
                help: t('Displays encounters/hour, revenue, experience rates when returning from combat', '从战斗返回时显示每小时遇敌数、收入、经验率'),
            },
            combatSim: {
                id: 'combatSim',
                label: t('Combat Simulator', '战斗模拟器'),
                type: 'checkbox',
                default: true,
                help: t('Simulate combat encounters to estimate XP/hr, deaths, and consumable usage', '模拟战斗遭遇以估算经验/小时、死亡次数和消耗品使用情况'),
            },
            combatSim_defaultHours: {
                id: 'combatSim_defaultHours',
                label: t('Combat Simulator: Default hours (single zone)', '战斗模拟器: 默认小时数（单区域）'),
                type: 'number',
                default: 100,
                min: 1,
                max: 10000,
                step: 1,
                help: t('Default simulation duration in hours for single-zone runs', '单区域运行的默认模拟持续时间（小时）'),
            },
            combatSim_allZonesDefaultHours: {
                id: 'combatSim_allZonesDefaultHours',
                label: t('Combat Simulator: Default hours (All Zones)', '战斗模拟器: 默认小时数（所有区域）'),
                type: 'number',
                default: 10,
                min: 1,
                max: 10000,
                step: 1,
                help: t('Default simulation duration in hours for All Zones runs', '所有区域运行的默认模拟持续时间（小时）'),
            },
            combatSim_seekDefaultHours: {
                id: 'combatSim_seekDefaultHours',
                label: t('Combat Simulator: Default hours (Seek)', '战斗模拟器: 默认小时数（寻敌）'),
                type: 'number',
                default: 10,
                min: 1,
                max: 10000,
                step: 1,
                help: t('Default simulation duration in hours for Seek Best Source runs', '寻找最佳来源运行的默认模拟持续时间（小时）'),
            },
            combatSim_decimalMinutes: {
                id: 'combatSim_decimalMinutes',
                label: t('Combat Simulator: Show completion time as decimal minutes', '战斗模拟器: 以十进制分钟显示完成时间'),
                type: 'checkbox',
                default: false,
                help: t('Display avg completion time as "X.XX min" instead of "Xm Ys"', '将平均完成时间显示为“X.XX 分钟”而不是“X分 Y秒”'),
            },
            combatStats: {
                id: 'combatStats',
                label: t('Combat Statistics: Show Statistics tab in Combat panel', '战斗统计: 在战斗面板中显示统计标签页'),
                type: 'checkbox',
                default: true,
                help: t('Adds a Statistics button to the Combat panel showing income, profit, consumable costs, EXP, and drop details', '在战斗面板中添加一个统计按钮，显示收入、利润、消耗品成本、经验和掉落详情'),
            },
            combatStatsChatMessage: {
                id: 'combatStatsChatMessage',
                label: t('Combat Statistics: Chat message format', '战斗统计: 聊天消息格式'),
                type: 'template',
                default: [
                    { type: 'text', value: t('Combat Stats: ', '战斗统计: ') },
                    { type: 'variable', key: '{duration}', label: t('Duration', '持续时间') },
                    { type: 'text', value: t(' duration | ', ' 持续时间 | ') },
                    { type: 'variable', key: '{encountersPerHour}', label: t('Encounters/Hour', '每小时遇敌数') },
                    { type: 'text', value: t(' EPH | ', ' 遇敌/小时 | ') },
                    { type: 'variable', key: '{income}', label: t('Total Income', '总收入') },
                    { type: 'text', value: t(' income | ', ' 收入 | ') },
                    { type: 'variable', key: '{dailyIncome}', label: t('Daily Income', '每日收入') },
                    { type: 'text', value: t(' income/d | ', ' 收入/天 | ') },
                    { type: 'variable', key: '{dailyConsumableCosts}', label: t('Daily Consumable Costs', '每日消耗品成本') },
                    { type: 'text', value: t(' consumables/d | ', ' 消耗品/天 | ') },
                    { type: 'variable', key: '{dailyProfit}', label: t('Daily Profit', '每日利润') },
                    { type: 'text', value: t(' profit/d | ', ' 利润/天 | ') },
                    { type: 'variable', key: '{exp}', label: t('EXP/Hour', '经验/小时') },
                    { type: 'text', value: t(' exp/h | ', ' 经验/小时 | ') },
                    { type: 'variable', key: '{deathCount}', label: t('Deaths', '死亡次数') },
                    { type: 'text', value: t(' deaths', ' 死亡') },
                ],
                help: t('Message format when Ctrl+clicking player card in Statistics. Click "Edit Template" to customize.', '在统计中按 Ctrl+点击 玩家卡片时的消息格式。点击“编辑模板”进行自定义。'),
                templateVariables: [
                    { key: '{duration}', label: t('Duration', '持续时间'), description: t('Combat session duration', '战斗会话持续时间') },
                    { key: '{encountersPerHour}', label: t('Encounters/Hour', '每小时遇敌数'), description: t('Encounters per hour (EPH)', '每小时遇敌数 (EPH)') },
                    { key: '{income}', label: t('Total Income', '总收入'), description: t('Total income from combat', '来自战斗的总收入') },
                    { key: '{dailyIncome}', label: t('Daily Income', '每日收入'), description: t('Income per day', '每天的收入') },
                    {
                        key: '{dailyConsumableCosts}',
                        label: t('Daily Consumable Costs', '每日消耗品成本'),
                        description: t('Consumable costs per day', '每天的消耗品成本'),
                    },
                    { key: '{dailyProfit}', label: t('Daily Profit', '每日利润'), description: t('Profit per day', '每天的利润') },
                    { key: '{exp}', label: t('EXP/Hour', '经验/小时'), description: t('Experience per hour', '每小时的经验') },
                    { key: '{deathCount}', label: t('Deaths', '死亡次数'), description: t('Number of deaths', '死亡次数') },
                ],
            },
        },
    },

    tasks: {
        title: t('Tasks', '任务'),
        icon: '📋',
        settings: {
            taskProfitCalculator: {
                id: 'taskProfitCalculator',
                label: t('Show total profit for gathering/production tasks', '显示采集/生产任务的总利润'),
                type: 'checkbox',
                default: true,
            },
            taskEfficiencyRating: {
                id: 'taskEfficiencyRating',
                label: t('Show task efficiency rating (tokens/profit per hour)', '显示任务效率评级（代币/利润 每小时）'),
                type: 'checkbox',
                default: true,
                help: t('Displays a color-graded efficiency score based on expected completion time.', '显示基于预期完成时间的颜色分级效率分数。'),
            },
            taskMaterialsIndicator: {
                id: 'taskMaterialsIndicator',
                label: t('Show materials availability on production tasks', '在生产任务上显示材料可用性'),
                type: 'checkbox',
                default: true,
                help: t('Shows how many task actions you can complete with current inventory.', '显示使用当前库存可以完成多少次任务行动。'),
            },
            taskEfficiencyRatingMode: {
                id: 'taskEfficiencyRatingMode',
                label: t('Efficiency algorithm', '效率算法'),
                type: 'select',
                default: 'gold',
                options: [
                    { value: 'tokens', label: t('Task tokens per hour', '每小时任务代币') },
                    { value: 'gold', label: t('Task profit per hour', '每小时任务利润') },
                ],
                help: t('Choose whether to rate by task token payout or total profit.', '选择是按任务代币支出还是按总利润进行评级。'),
            },
            taskEfficiencyGradient: {
                id: 'taskEfficiencyGradient',
                label: t('Use relative gradient colors', '使用相对渐变色'),
                type: 'checkbox',
                default: false,
                help: t('Colors efficiency ratings relative to visible tasks.', '相对于可见任务为效率评级着色。'),
            },
            taskQueuedIndicator: {
                id: 'taskQueuedIndicator',
                label: t('Show "Queued" indicator on task cards', '在任务卡片上显示“排队中”指示器'),
                type: 'checkbox',
                default: true,
                help: t('Displays a status message on task cards when their action is in your action queue', '当任务对应的行动在您的行动队列中时，在任务卡片上显示状态消息'),
            },
            taskRerollTracker: {
                id: 'taskRerollTracker',
                label: t('Track task reroll costs', '追踪任务重置成本'),
                type: 'checkbox',
                default: true,
                help: t('Tracks how much gold/cowbells spent rerolling each task (EXPERIMENTAL - may cause UI freezing)', '追踪重置每个任务花费了多少金币/牛铃（实验性功能 - 可能导致界面卡顿）'),
            },
            taskMapIndex: {
                id: 'taskMapIndex',
                label: t('Show combat zone index numbers on tasks', '在任务上显示战斗区域索引号'),
                type: 'checkbox',
                default: true,
            },
            taskIcons: {
                id: 'taskIcons',
                label: t('Show visual icons on task cards', '在任务卡片上显示视觉图标'),
                type: 'checkbox',
                default: true,
                help: t('Displays semi-transparent item/monster icons on task cards', '在任务卡片上显示半透明的物品/怪物图标'),
            },
            taskIconsDungeons: {
                id: 'taskIconsDungeons',
                label: t('Show dungeon icons on combat tasks', '在战斗任务上显示副本图标'),
                type: 'checkbox',
                default: false,
                help: 'Shows which dungeons contain the monster (requires Task Icons enabled)',
            },
            taskSorter_autoSort: {
                id: 'taskSorter_autoSort',
                label: t('Automatically sort tasks when opening task panel', '打开任务面板时自动排序任务'),
                type: 'checkbox',
                default: false,
                help: t('Automatically sorts tasks by skill type when you open the task panel', '打开任务面板时自动按技能类型对任务进行排序'),
            },
            taskSorter_hideButton: {
                id: 'taskSorter_hideButton',
                label: t('Hide Sort Tasks button', '隐藏“排序任务”按钮'),
                type: 'checkbox',
                default: false,
                help: t('Hides the Sort Tasks button while keeping auto-sort functional', '隐藏“排序任务”按钮，但保持自动排序功能'),
            },
            taskSorter_sortMode: {
                id: 'taskSorter_sortMode',
                label: t('Task sort mode', '任务排序模式'),
                type: 'select',
                default: 'skill',
                options: [
                    { value: 'skill', label: t('Skill / Zone', '技能 / 区域') },
                    { value: 'time', label: t('Time to Completion', '完成时间') },
                ],
                help: t('How tasks are ordered when clicking Sort Tasks. "Time to Completion" sorts fastest tasks first; combat and completed tasks go to the bottom.', '点击“排序任务”时任务的排列方式。“完成时间”将最快完成的任务排在前面；战斗和已完成的任务排在底部。'),
            },
            taskInventoryHighlighter: {
                id: 'taskInventoryHighlighter',
                label: t('Enable Task Inventory Highlighter button', '启用任务库存高亮按钮'),
                type: 'checkbox',
                default: true,
                help: t('Adds a button to dim inventory items not needed for your current non-combat tasks', '添加一个按钮，使当前非战斗任务不需要的库存物品变暗'),
            },
            taskStatistics: {
                id: 'taskStatistics',
                label: t('Show task statistics button on Tasks panel', '在任务面板上显示任务统计按钮'),
                type: 'checkbox',
                default: true,
                help: t('Adds a Statistics button to the Tasks panel showing overflow time, expected rewards, and completion estimates', '在任务面板上添加一个统计按钮，显示溢出时间、预期奖励和完成预估'),
            },
            taskClaimCollector: {
                id: 'taskClaimCollector',
                label: t('Move Claim Reward buttons to top of task list', '将领取奖励按钮移至任务列表顶部'),
                type: 'checkbox',
                default: true,
                help: t('Moves all Claim Reward buttons to a stack at the top of the task list so you can click the same spot repeatedly to claim all completed tasks', '将所有“领取奖励”按钮移到任务列表顶部的堆栈中，以便您可以重复点击同一位置来领取所有已完成的任务'),
            },
            taskGoMerge: {
                id: 'taskGoMerge',
                label: t('Merge duplicate tasks on Go', '点击“前往”时合并重复任务'),
                type: 'checkbox',
                default: true,
                help: t('When clicking Go on a task, combines the required amounts of all in-progress tasks for the same action into a single pre-filled count', '当点击任务的“前往”时，将相同行动的所有进行中任务的所需数量合并为单个预填数量'),
            },
            taskRerollProtection: {
                id: 'taskRerollProtection',
                label: t('Task reroll protection', '任务重置保护'),
                type: 'checkbox',
                default: true,
                help: t('Protect specific tasks from accidental rerolling. Protected tasks get a green highlight and require a confirmation click before rerolling. A shield icon appears in the task panel to configure protected zones.', '保护特定任务免遭意外重置。受保护的任务会获得绿色高亮显示，并且在重置前需要点击确认。任务面板中会出现一个盾牌图标，用于配置受保护的区域。'),
            },
        },
    },

    ui: {
        title: t('UI Enhancements', '用户界面增强'),
        icon: '🎨',
        settings: {
            formatting_useKMBFormat: {
                id: 'formatting_useKMBFormat',
                label: t('Use K/M/B number formatting (e.g., 1.5M instead of 1,500,000)', '使用 K/M/B 数字格式（例如：1.5M 而不是 1,500,000）'),
                type: 'checkbox',
                default: true,
                help: t('Applies to tooltips, action panels, profit displays, and all number formatting throughout the UI', '适用于工具提示、行动面板、利润显示以及整个界面的所有数字格式'),
            },
            ui_externalLinks: {
                id: 'ui_externalLinks',
                label: t('Left sidebar: Show external tool links', '左侧边栏: 显示外部工具链接'),
                type: 'checkbox',
                default: true,
                help: t('Adds quick links to Combat Sim, Market Tracker, Enhancelator, and Milkonomy', '添加指向战斗模拟器、市场追踪器、强化计算器和 Milkonomy 的快速链接'),
            },
            hideLabyrinthBadge: {
                id: 'hideLabyrinthBadge',
                label: t('Left sidebar: Hide Labyrinth ping badge', '左侧边栏: 隐藏迷宫红点徽章'),
                type: 'checkbox',
                default: false,
            },
            tabReorder: {
                id: 'tabReorder',
                label: t('Character panel: Drag-and-drop tab reordering', '角色面板: 拖放重新排序标签页'),
                type: 'checkbox',
                default: true,
                help: t('Drag tabs to rearrange the order of Inventory, Toolasha, Equipment, Houses, Abilities, and Loadout. Order persists through refresh.', '拖动标签页以重新排列库存、Toolasha、装备、房屋、技能和预设的顺序。顺序在刷新后保留。'),
            },
            expPercentage: {
                id: 'expPercentage',
                label: t('Left sidebar: Show skill XP percentages', '左侧边栏: 显示技能经验百分比'),
                type: 'checkbox',
                default: true,
            },
            itemIconLevel: {
                id: 'itemIconLevel',
                label: t('Bottom left corner of icons: Show equipment level', '图标左下角: 显示装备等级'),
                type: 'checkbox',
                default: true,
            },
            loadoutEnhancementDisplay: {
                id: 'loadoutEnhancementDisplay',
                label: t('Loadout panel: Show highest-owned enhancement level on equipment icons', '预设面板: 在装备图标上显示拥有的最高强化等级'),
                type: 'checkbox',
                default: true,
            },
            loadout_sortEnabled: {
                id: 'loadout_sortEnabled',
                label: t('Loadout panel: Enable drag-and-drop reordering', '预设面板: 启用拖放重新排序'),
                type: 'checkbox',
                default: true,
            },
            loadoutSnapshot: {
                id: 'loadoutSnapshot',
                label: t('Loadout panel: Use saved loadout snapshots in profit calculations', '预设面板: 在利润计算中使用保存的预设快照'),
                type: 'checkbox',
                default: true,
                help: t('Saves your loadout equipment when you view loadouts, so profit/hr calculations use the correct tool bonuses even when that loadout is not equipped. Disable to always use currently-equipped gear.', '查看预设时保存您的预设装备，以便即使未装备该预设，利润/小时计算也会使用正确的工具加成。禁用以始终使用当前装备的物品。'),
            },
            showsKeyInfoInIcon: {
                id: 'showsKeyInfoInIcon',
                label: t('Bottom left corner of key icons: Show zone index', '钥匙图标左下角: 显示区域索引'),
                type: 'checkbox',
                default: true,
            },
            mapIndex: {
                id: 'mapIndex',
                label: t('Combat zones: Show zone index numbers', '战斗区域: 显示区域索引号'),
                type: 'checkbox',
                default: true,
            },
            alchemyItemDimming: {
                id: 'alchemyItemDimming',
                label: t('Alchemy panel: Dim items requiring higher level', '炼金面板: 使需要更高等级的物品变暗'),
                type: 'checkbox',
                default: true,
            },
            marketFilter: {
                id: 'marketFilter',
                label: t('Marketplace: Filter by level, class, slot', '市场: 按等级、职业、部位过滤'),
                type: 'checkbox',
                default: true,
            },
            marketSort: {
                id: 'marketSort',
                label: t('Marketplace: Sort items by profitability', '市场: 按盈利能力对物品进行排序'),
                type: 'checkbox',
                default: true,
                help: t('Adds a button to sort marketplace items by profit/hour. Items without profit data (drop-only) appear at the end.', '添加一个按钮以按利润/小时对市场物品进行排序。没有利润数据（仅掉落）的物品显示在最后。'),
            },
            fillMarketOrderPrice: {
                id: 'fillMarketOrderPrice',
                label: t('Auto-fill marketplace orders with optimal price', '自动以最佳价格填充市场订单'),
                type: 'checkbox',
                default: true,
            },
            market_autoFillSellStrategy: {
                id: 'market_autoFillSellStrategy',
                label: t('Auto-fill sell price strategy', '自动填充卖出价策略'),
                type: 'select',
                default: 'match',
                options: [
                    { value: 'match', label: t('Match best sell price', '匹配最佳卖出价') },
                    { value: 'undercut', label: t('Undercut by 1 (best sell - 1)', '压价 1（最佳卖出 - 1）') },
                ],
                help: t('When creating sell listings, choose whether to match or undercut the current best sell price', '创建卖出列表时，选择是匹配还是压低当前最佳卖出价'),
            },
            market_autoFillBuyStrategy: {
                id: 'market_autoFillBuyStrategy',
                label: t('Auto-fill buy price strategy', '自动填充买入价策略'),
                type: 'select',
                default: 'outbid',
                options: [
                    { value: 'outbid', label: t('Outbid by 1 (best buy + 1)', '加价 1（最佳买入 + 1）') },
                    { value: 'match', label: t('Match best buy price', '匹配最佳买入价') },
                    { value: 'undercut', label: t('Undercut by 1 (best buy - 1)', '压价 1（最佳买入 - 1）') },
                ],
                help: t('When creating buy listings, choose whether to outbid, match, or undercut the current best buy price', '创建买入列表时，选择是加价、匹配还是低于当前最佳买入价'),
            },
            market_autoClickMax: {
                id: 'market_autoClickMax',
                label: t('Auto-click Max button on sell listing dialogs', '在卖出列表对话框上自动点击“最大”按钮'),
                type: 'checkbox',
                default: true,
                help: t('Automatically clicks the Max button in the quantity field when opening Sell listing dialogs', '打开卖出列表对话框时，自动点击数量字段中的“最大”按钮'),
            },
            market_quickInputButtons: {
                id: 'market_quickInputButtons',
                label: t('Marketplace: Quick input buttons on order dialogs', '市场: 订单对话框上的快捷输入按钮'),
                type: 'checkbox',
                default: true,
                help: t('Adds 10, 100, 1000 preset quantity buttons to buy/sell dialogs', '向买入/卖出对话框添加 10, 100, 1000 预设数量按钮'),
            },
            market_marketplaceShortcuts: {
                id: 'market_marketplaceShortcuts',
                label: t('Marketplace: Show "Marketplace Action" button on item menus', '市场: 在物品菜单上显示“市场操作”按钮'),
                type: 'checkbox',
                default: true,
                help: t('Adds a Marketplace Action dropdown to item menus with Sell Now, Buy Now, and listing shortcuts', '在物品菜单中添加一个“市场操作”下拉菜单，包含“立即卖出”、“立即买入”和列表快捷方式'),
            },
            market_visibleItemCount: {
                id: 'market_visibleItemCount',
                label: t('Market: Show inventory count on items', '市场: 在物品上显示库存数量'),
                type: 'checkbox',
                default: true,
                help: t('Displays how many of each item you own when browsing the market', '浏览市场时显示您拥有每件物品的数量'),
            },
            market_visibleItemCountOpacity: {
                id: 'market_visibleItemCountOpacity',
                label: t('Market: Opacity for items not in inventory', '市场: 库存中没有的物品的透明度'),
                type: 'slider',
                default: 0.25,
                min: 0,
                max: 1,
                step: 0.05,
                help: t('How transparent item tiles appear when you own zero of that item', '当您没有该物品时，物品卡片的透明度如何'),
            },
            market_visibleItemCountIncludeEquipped: {
                id: 'market_visibleItemCountIncludeEquipped',
                label: t('Market: Count equipped items', '市场: 计算已装备的物品'),
                type: 'checkbox',
                default: true,
                help: t('Include currently equipped items in the displayed count', '在显示的计数中包含当前装备的物品'),
            },
            market_showListingPrices: {
                id: 'market_showListingPrices',
                label: t('Market: Show prices on individual listings', '市场: 显示各个列表的价格'),
                type: 'checkbox',
                default: true,
                help: t('Displays top order price and total value on each listing in My Listings table', '在“我的列表”表格中的每个列表上显示最高订单价格和总价值'),
            },
            market_tradeHistory: {
                id: 'market_tradeHistory',
                label: t('Market: Show personal trade history', '市场: 显示个人交易历史'),
                type: 'checkbox',
                default: true,
                help: t('Displays your last buy/sell prices for items in marketplace', '在市场中显示您上次买入/卖出物品的价格'),
            },
            market_tradeHistoryComparisonMode: {
                id: 'market_tradeHistoryComparisonMode',
                label: t('Market: Trade history comparison mode', '市场: 交易历史比较模式'),
                type: 'select',
                default: 'instant',
                options: [
                    { value: 'instant', label: t('Instant', '即时') },
                    { value: 'listing', label: t('Orders', '订单') },
                ],
                help: t('Instant: Compare to instant buy/sell prices. Orders: Compare to buy/sell orders.', '即时：与即时买入/卖出价进行比较。订单：与买入/卖出订单进行比较。'),
            },
            market_listingPricePrecision: {
                id: 'market_listingPricePrecision',
                label: t('Market: Listing price decimal precision', '市场: 列表价格小数精度'),
                type: 'number',
                default: 2,
                min: 0,
                max: 4,
                help: t('Number of decimal places to show for listing prices', '列表价格显示的小数位数'),
            },
            market_showListingAge: {
                id: 'market_showListingAge',
                label: t('Market: Show listing age on My Listings', '市场: 在“我的列表”上显示列表时长'),
                type: 'checkbox',
                default: false,
                help: t('Display how long ago each listing was created on the My Listings tab (e.g., "3h 45m")', '在“我的列表”标签页上显示每个列表创建了多长时间（例如，“3小时45分钟”）'),
            },
            market_showTopOrderAge: {
                id: 'market_showTopOrderAge',
                label: t('Market: Show top order age on My Listings', '市场: 在“我的列表”上显示最高订单时长'),
                type: 'checkbox',
                default: false,
                help: t('Display estimated age of the top competing order for each of your listings (requires estimated listing age feature to be active)', '显示每个列表的最高竞争订单的估计时长（需要启用估计列表时长功能）'),
            },
            market_showEstimatedListingAge: {
                id: 'market_showEstimatedListingAge',
                label: t('Market: Show estimated age on order book', '市场: 在订单簿上显示估计时长'),
                type: 'checkbox',
                default: true,
                help: t('Estimates creation time for all market listings using listing ID interpolation', '使用列表 ID 插值估计所有市场列表的创建时间'),
            },
            market_listingAgeFormat: {
                id: 'market_listingAgeFormat',
                label: t('Market: Listing age display format', '市场: 列表时长显示格式'),
                type: 'select',
                default: 'datetime',
                options: [
                    { value: 'elapsed', label: t('Elapsed Time (e.g., "3h 45m")', '经过时间（例如："3小时45分钟"）') },
                    { value: 'datetime', label: t('Date/Time (e.g., "01-13 14:30")', '日期/时间（例如："01-13 14:30"）') },
                ],
                help: t('Choose how to display listing creation times', '选择如何显示列表创建时间'),
            },
            market_listingTimeFormat: {
                id: 'market_listingTimeFormat',
                label: t('Market: Time format for date/time display', '市场: 日期/时间显示的时间格式'),
                type: 'select',
                default: '24hour',
                options: [
                    { value: '24hour', label: t('24-hour (14:30)', '24小时制 (14:30)') },
                    { value: '12hour', label: t('12-hour (2:30 PM)', '12小时制 (2:30 PM)') },
                ],
                help: t('Time format when using Date/Time display (only applies if Date/Time format is selected)', '使用日期/时间显示时的时间格式（仅在选择了日期/时间格式时适用）'),
            },
            market_listingDateFormat: {
                id: 'market_listingDateFormat',
                label: t('Market: Date format for date/time display', '市场: 日期/时间显示的日期格式'),
                type: 'select',
                default: 'MM-DD',
                options: [
                    { value: 'MM-DD', label: t('MM-DD (01-13)', '月-日 (01-13)') },
                    { value: 'DD-MM', label: t('DD-MM (13-01)', '日-月 (13-01)') },
                ],
                help: t('Date format when using Date/Time display (only applies if Date/Time format is selected)', '使用日期/时间显示时的日期格式（仅在选择了日期/时间格式时适用）'),
            },
            market_showOrderTotals: {
                id: 'market_showOrderTotals',
                label: t('Market: Show order totals in header', '市场: 在头部显示订单总额'),
                type: 'checkbox',
                default: true,
                help: t('Displays buy orders (BO), sell orders (SO), and unclaimed coins (💰) in the header area below gold', '在金币下方的头部区域显示买入订单 (BO)、卖出订单 (SO) 和未领取的硬币 (💰)'),
            },
            market_showHistoryViewer: {
                id: 'market_showHistoryViewer',
                label: t('Market: Show history viewer button in settings', '市场: 在设置中显示历史查看器按钮'),
                type: 'checkbox',
                default: true,
                help: t('Adds "View Market History" button to settings panel for viewing and exporting all market listing history', '在设置面板中添加“查看市场历史”按钮，用于查看和导出所有市场列表历史记录'),
            },
            market_showPhiloCalculator: {
                id: 'market_showPhiloCalculator',
                label: t('Market: Show Philo Gamba calculator button in settings', '市场: 在设置中显示点金石计算器按钮'),
                type: 'checkbox',
                default: true,
                help: t('Adds "Philo Gamba" button to settings panel for calculating transmutation ROI into Philosopher\'s Stones', '在设置面板中添加“点金石赌注”按钮，用于计算转化为点金石的投资回报率'),
            },
            market_showQueueLength: {
                id: 'market_showQueueLength',
                label: t('Market: Show queue length estimates', '市场: 显示队列长度估计'),
                type: 'checkbox',
                default: true,
                help: t('Displays total quantity at best price below Buy/Sell buttons. Estimated values (20+ orders at same price) are shown in a different color.', '在买入/卖出按钮下方显示最佳价格的总数量。估计值（同一价格有20个以上订单）将以不同的颜色显示。'),
            },
            market_milkywayMarketLink: {
                id: 'market_milkywayMarketLink',
                label: t('Market: Show MilkyWay Market link', '市场: 显示 MilkyWay 市场链接'),
                type: 'checkbox',
                default: false,
                help: t('Adds a small link to view the current item on milkyway.market', '添加一个小链接以在 milkyway.market 上查看当前物品'),
            },
            itemDictionary_transmuteRates: {
                id: 'itemDictionary_transmuteRates',
                label: t('Item Dictionary: Show transmutation success rates', '物品字典: 显示转化成功率'),
                type: 'checkbox',
                default: true,
                help: t('Displays success rate percentages in the "Transmuted From (Alchemy)" section', '在“转化自（炼金术）”部分显示成功率百分比'),
            },
            itemDictionary_transmuteIncludeBaseRate: {
                id: 'itemDictionary_transmuteIncludeBaseRate',
                label: t('Item Dictionary: Include base success rate in transmutation percentages', '物品字典: 在转化百分比中包含基础成功率'),
                type: 'checkbox',
                default: true,
                help: t('When enabled, shows total probability (base rate × drop rate). When disabled, shows conditional probability (drop rate only, matching "Transmutes Into" section)', '启用后，显示总概率（基础概率 × 掉落概率）。禁用后，显示条件概率（仅掉落概率，与“转化为”部分匹配）'),
            },
        },
    },

    guild: {
        title: t('Guild', '公会'),
        icon: '👥',
        settings: {
            guildXPTracker: {
                id: 'guildXPTracker',
                label: t('Track guild and member XP over time', '随着时间的推移追踪公会和成员的经验'),
                type: 'checkbox',
                default: true,
                help: t('Records guild and member XP data from WebSocket messages for XP/hr calculations', '从 WebSocket 消息中记录公会和成员的经验数据以用于经验/小时的计算'),
            },
            guildXPDisplay: {
                id: 'guildXPDisplay',
                label: t('Show XP/hr stats on Guild panel and Leaderboard', '在公会面板和排行榜上显示经验/小时统计数据'),
                type: 'checkbox',
                default: true,
                help: t('Displays XP/hr rates, rankings, and a weekly chart on the Guild Overview, Members, and Guild Leaderboard tabs. Disable the standalone Guild XP/h userscript if using this.', '在公会概览、成员和公会排行榜标签页上显示经验/小时比率、排名和每周图表。如果使用此功能，请禁用独立的“Guild XP/h”用户脚本。'),
            },
        },
    },

    house: {
        title: t('House', '房屋'),
        icon: '🏠',
        settings: {
            houseUpgradeCosts: {
                id: 'houseUpgradeCosts',
                label: t('Show upgrade costs with market prices and inventory comparison', '显示包含市场价格和库存对比的升级成本'),
                type: 'checkbox',
                default: true,
            },
        },
    },

    notifications: {
        title: t('Notifications', '通知'),
        icon: '🔔',
        settings: {
            notifiEmptyAction: {
                id: 'notifiEmptyAction',
                label: t('Browser notification when action queue is empty', '行动队列为空时的浏览器通知'),
                type: 'checkbox',
                default: false,
                help: t('Only works when the game page is open', '仅在游戏页面打开时有效'),
            },
        },
    },

    colors: {
        title: t('Color Customization', '颜色自定义'),
        icon: '🎨',
        settings: {
            color_profit: {
                id: 'color_profit',
                label: t('Profit/Positive Values', '利润/正值'),
                type: 'color',
                default: '#047857',
                help: t('Color used for profit, gains, and positive values', '用于利润、收益和正值的颜色'),
            },
            color_loss: {
                id: 'color_loss',
                label: t('Loss/Negative Values', '亏损/负值'),
                type: 'color',
                default: '#f87171',
                help: t('Color used for losses, costs, and negative values', '用于亏损、成本和负值的颜色'),
            },
            color_warning: {
                id: 'color_warning',
                label: t('Warnings', '警告'),
                type: 'color',
                default: '#ffa500',
                help: t('Color used for warnings and important notices', '用于警告和重要通知的颜色'),
            },
            color_info: {
                id: 'color_info',
                label: t('Informational', '信息'),
                type: 'color',
                default: '#60a5fa',
                help: t('Color used for informational text and highlights', '用于信息文本和高亮的颜色'),
            },
            color_essence: {
                id: 'color_essence',
                label: t('Essences', '精华'),
                type: 'color',
                default: '#c084fc',
                help: t('Color used for essence drops and essence-related text', '用于精华掉落和精华相关文本的颜色'),
            },
            color_tooltip_profit: {
                id: 'color_tooltip_profit',
                label: t('Tooltip Profit/Positive', '工具提示 利润/正值'),
                type: 'color',
                default: '#047857',
                help: t('Color for profit/positive values in tooltips (light backgrounds)', '工具提示中利润/正值的颜色（浅色背景）'),
            },
            color_tooltip_loss: {
                id: 'color_tooltip_loss',
                label: t('Tooltip Loss/Negative', '工具提示 亏损/负值'),
                type: 'color',
                default: '#dc2626',
                help: t('Color for loss/negative values in tooltips (light backgrounds)', '工具提示中亏损/负值的颜色（浅色背景）'),
            },
            color_tooltip_info: {
                id: 'color_tooltip_info',
                label: t('Tooltip Informational', '工具提示 信息'),
                type: 'color',
                default: '#2563eb',
                help: t('Color for informational text in tooltips (light backgrounds)', '工具提示中信息文本的颜色（浅色背景）'),
            },
            color_tooltip_warning: {
                id: 'color_tooltip_warning',
                label: t('Tooltip Warnings', '工具提示 警告'),
                type: 'color',
                default: '#ea580c',
                help: t('Color for warnings in tooltips (light backgrounds)', '工具提示中警告的颜色（浅色背景）'),
            },
            color_text_primary: {
                id: 'color_text_primary',
                label: t('Primary Text', '主要文本'),
                type: 'color',
                default: '#ffffff',
                help: t('Main text color', '主文本颜色'),
            },
            color_text_secondary: {
                id: 'color_text_secondary',
                label: t('Secondary Text', '次要文本'),
                type: 'color',
                default: '#888888',
                help: t('Dimmed/secondary text color', '变暗/次要的文本颜色'),
            },
            color_border: {
                id: 'color_border',
                label: t('Borders', '边框'),
                type: 'color',
                default: '#444444',
                help: t('Border and separator color', '边框和分隔符颜色'),
            },
            color_gold: {
                id: 'color_gold',
                label: t('Gold/Currency', '金币/货币'),
                type: 'color',
                default: '#ffa500',
                help: t('Color used for gold and currency displays', '用于金币和货币显示的颜色'),
            },
            color_mirror: {
                id: 'color_mirror',
                label: t("Philosopher's Mirror", "贤者之镜"),
                type: 'color',
                default: '#ffd700',
                help: t("Color for the Philosopher's Mirror usage line in enhancement tooltips", "强化工具提示中贤者之镜使用情况行的颜色"),
            },
            color_listing_price_1m: {
                id: 'color_listing_price_1m',
                label: t('Listing Total: 1M+', '列表总价: 1M+'),
                type: 'color',
                default: '#ffd700',
                help: t('Color for market listing total prices of 1 million or more', '市场列表总价在 100 万或以上的颜色'),
            },
            color_listing_price_100k: {
                id: 'color_listing_price_100k',
                label: t('Listing Total: 100K+', '列表总价: 100K+'),
                type: 'color',
                default: '#22c55e',
                help: t('Color for market listing total prices of 100K or more', '市场列表总价在 10 万或以上的颜色'),
            },
            color_listing_price_10k: {
                id: 'color_listing_price_10k',
                label: t('Listing Total: 10K+', '列表总价: 10K+'),
                type: 'color',
                default: '#ffffff',
                help: t('Color for market listing total prices of 10K or more', '市场列表总价在 1 万或以上的颜色'),
            },
            color_listing_price_low: {
                id: 'color_listing_price_low',
                label: t('Listing Total: <10K', '列表总价: <10K'),
                type: 'color',
                default: '#888888',
                help: t('Color for market listing total prices under 10K', '市场列表总价在 1 万以下的颜色'),
            },
            color_accent: {
                id: 'color_accent',
                label: t('Script Accent Color', '脚本强调色'),
                type: 'color',
                default: '#22c55e',
                help: t('Primary accent color for script UI elements (buttons, headers, zone numbers, XP percentages, etc.)', '脚本用户界面元素的主要强调色（按钮、标题、区域编号、经验百分比等）'),
            },
            color_remaining_xp: {
                id: 'color_remaining_xp',
                label: t('Remaining XP Text', '剩余经验文本'),
                type: 'color',
                default: '#FFFFFF',
                help: t('Color for remaining XP text below skill bars in left navigation', '左侧导航中技能栏下方剩余经验文本的颜色'),
            },
            color_xp_rate: {
                id: 'color_xp_rate',
                label: t('XP Rate Text', '经验速率文本'),
                type: 'color',
                default: '#ffffff',
                help: t('Color for XP/hr rate text on skill bars in left navigation', '左侧导航中技能栏上经验/小时比率文本的颜色'),
            },
            color_hours_to_level: {
                id: 'color_hours_to_level',
                label: t('Hours to Level Text', '升级所需小时数文本'),
                type: 'color',
                default: '#ffffff',
                help: t('Color for "hours till next level" text in skill tooltips', '技能工具提示中“距离下一等级所需小时数”文本的颜色'),
            },
            color_inv_count: {
                id: 'color_inv_count',
                label: t('Inventory Count Text', '库存计数文本'),
                type: 'color',
                default: '#ffffff',
                help: t('Color for inventory count shown on action tiles and in the action detail panel', '在行动卡片和行动详情面板上显示的库存计数颜色'),
            },
            color_invBadge_ask: {
                id: 'color_invBadge_ask',
                label: t('Inventory Badge: Ask Price', '库存徽章: 卖出价'),
                type: 'color',
                default: '#047857',
                help: t('Color for Ask price badges on inventory items (seller asking price - better selling value)', '库存物品上卖出价徽章的颜色（卖方要价 - 更好的售价）'),
            },
            color_invBadge_bid: {
                id: 'color_invBadge_bid',
                label: t('Inventory Badge: Bid Price', '库存徽章: 买入价'),
                type: 'color',
                default: '#60a5fa',
                help: t('Color for Bid price badges on inventory items (buyer bid price - instant-sell value)', '库存物品上买入价徽章的颜色（买方出价 - 立即售出价值）'),
            },
            color_transmute: {
                id: 'color_transmute',
                label: t('Transmutation Rates', '转化成功率'),
                type: 'color',
                default: '#ffffff',
                help: t('Color used for transmutation success rate percentages in Item Dictionary', '物品字典中转化成功率百分比的颜色'),
            },
            color_queueLength_known: {
                id: 'color_queueLength_known',
                label: t('Queue Length: Known Value', '队列长度: 已知值'),
                type: 'color',
                default: '#ffffff',
                help: t('Color for known queue lengths (when all visible orders are counted)', '已知队列长度的颜色（当计算所有可见订单时）'),
            },
            color_queueLength_estimated: {
                id: 'color_queueLength_estimated',
                label: t('Queue Length: Estimated Value', '队列长度: 估计值'),
                type: 'color',
                default: '#60a5fa',
                help: t('Color for estimated queue lengths (extrapolated from 20+ orders at same price)', '估计队列长度的颜色（根据同一价格的 20 个以上订单推断）'),
            },
        },
    },

    collectionFilters: {
        title: t('Collection Filters', '收藏过滤'),
        icon: '⭐',
        settings: {
            collectionFilters: {
                id: 'collectionFilters',
                label: t('Enable Collection Filters & Favorites', '启用收藏过滤和收藏夹'),
                type: 'checkbox',
                default: true,
                help: t('Adds count-range filters, dungeon/skilling-outfit checkboxes, and favorites (★) to the Collections panel', '在收藏面板中添加数量范围过滤器、副本/技能套装复选框和收藏夹 (★)'),
            },
            collectionFilters_skillingBadges: {
                id: 'collectionFilters_skillingBadges',
                label: t('Show collection count badges on skilling action tiles', '在技能行动卡片上显示收藏数量徽章'),
                type: 'checkbox',
                default: true,
                help: t('Displays your collection count on skilling actions (open Collections once to populate counts)', '在技能行动上显示您的收藏数量（打开一次收藏面板以填充计数）'),
            },
        },
    },
};

/**
 * Get all setting IDs in order
 * @returns {string[]} Array of setting IDs
 */
export function getAllSettingIds() {
    const ids = [];
    for (const group of Object.values(settingsGroups)) {
        for (const settingId of Object.keys(group.settings)) {
            ids.push(settingId);
        }
    }
    return ids;
}

/**
 * Get a setting definition by ID
 * @param {string} settingId - Setting ID
 * @returns {Object|null} Setting definition or null
 */
export function getSettingDefinition(settingId) {
    for (const group of Object.values(settingsGroups)) {
        if (group.settings[settingId]) {
            return group.settings[settingId];
        }
    }
    return null;
}

/**
 * Check if a setting has dependencies
 * @param {string} settingId - Setting ID
 * @returns {string[]} Array of dependency setting IDs
 */
export function getSettingDependencies(settingId) {
    const def = getSettingDefinition(settingId);
    return def?.dependencies || [];
}
